version: "3"

services:
  label-studio:
    container_name: label-studio
    build: .
    working_dir: /label-studio
    volumes:
      - ./projects:/label-studio/projects
    command: "label-studio start-multi-session --root-dir=./projects --host 0.0.0.0"
    environment:
      - USERNAME=links
      - PASSWORD=datascience
    ports:
      - "127.0.0.1:8182:8080"
    restart: unless-stopped
